trigger:
- develop
- production

resources:
  repositories:
    - repository: liev-pipelines  
      type: git
      name: liev-pipelines

extends:
  template: '/liev-model-server-bedrock-stablediffusion.yml@liev-pipelines'